/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.List;
import models.CampoDeJuego;
import models.Comida;
import models.Veneno;
import sprite.Sprite;
import threads.HiloComida;
import threads.HiloVeneno;
import models.GestorPuntaje;
/**
 *
 * @author juans
 */

public class VentanaJuego extends javax.swing.JFrame {
    
    private CampoDeJuego campo;
    private JPanel panel;
    private int puntaje = 0;
    private int puntajeMaximo = 0;
    private static VentanaJuego instancia;

    /**
     * Creates new form ventanajuegoo
     */
    public VentanaJuego() {
        instancia = this;
        initComponents();
        iniciarJuego();
    }
    
    private void iniciarJuego() {
        campo = new CampoDeJuego();
        puntajeMaximo = models.GestorPuntaje.cargarPuntajeMaximo();


        panel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                campo.dibujarTodo(g);

                // Pintar puntaje
                g.setColor(Color.BLACK);
                g.setFont(new Font("Arial", Font.BOLD, 16));
                g.drawString("Puntaje: " + puntaje, 10, 20);
                g.drawString("Máximo: " + puntajeMaximo, 10, 40);

            }
        };

        // Escuchar clics del mouse para atrapar elementos
        panel.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                Sprite atrapado = campo.buscarElemento(e.getX(), e.getY());
                if (atrapado != null) {
                    if (atrapado instanceof Comida) {
                        puntaje += 1;
                    } else if (atrapado instanceof Veneno) {
                        puntaje -= 2;
                    }

                    // Actualizar puntaje máximo si aplica
                    actualizarPuntajeMaximo();
                    campo.removeSprite(atrapado);
                }

            }
        });

        this.setContentPane(panel);
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
        this.setVisible(true);

        // Iniciar los hilos de comida y veneno
        new Thread(new HiloComida(campo, panel)).start();
        new Thread(new HiloVeneno(campo, panel)).start();
    }
    
    public static void restarPuntoPorCaida() {
        instancia.puntaje -= 1;
        instancia.actualizarPuntajeMaximo();
    }

    private void actualizarPuntajeMaximo() {
        if (puntaje > puntajeMaximo) {
            puntajeMaximo = puntaje;
            GestorPuntaje.guardarPuntajeMaximo(puntajeMaximo);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaJuego().setVisible(true);
        });
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
